### ISSUE TITLE
Import OAI-PMH

### ISSUE THREAD

**Issue by jmeunierP8** [samszo/Omeka-S-theme-UOH#11]
Bonjour Samuel,
J'ai fait un nouvel essai d'import OAI-MPH avec <http://www.unit.eu/ori-oai-repository/OAIHandler> et j'obiens ce message d'erreur : 

Doctrine\ORM\EntityNotFoundException
Entity of type 'Omeka\Entity\Job' for IDs id(153) was not found

Détails :

Doctrine\ORM\EntityNotFoundException: Entity of type 'Omeka\Entity\Job' for IDs id(153) was not found in /var/www/html/uoh-psy/omkVide/vendor/doctrine/orm/lib/Doctrine/ORM/EntityNotFoundException.php:47
Stack trace:
#0 /var/www/html/uoh-psy/omkVide/vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php(166): Doctrine\ORM\EntityNotFoundException::fromClassNameAndIdentifier('Omeka\\Entity\\Jo...', Array)
#1 /var/www/html/uoh-psy/omkVide/application/data/doctrine-proxies/__CG__OmekaEntityJob.php(354): Doctrine\ORM\Proxy\ProxyFactory->Doctrine\ORM\Proxy\{closure}(Object(DoctrineProxies\__CG__\Omeka\Entity\Job), 'getStarted', Array)
#2 /var/www/html/uoh-psy/omkVide/application/data/doctrine-proxies/__CG__OmekaEntityJob.php(354): Closure->__invoke(Object(DoctrineProxies\__CG__\Omeka\Entity\Job), 'getStarted', Array)
#3 /var/www/html/uoh-psy/omkVide/application/src/Api/Representation/JobRepresentation.php(81): DoctrineProxies\__CG__\Omeka\Entity\Job->getStarted()
#4 /var/www/html/uoh-psy/omkVide/modules/OaiPmhHarvester/view/oai-pmh-harvester/admin/index/past-harvests.phtml(52): Omeka\Api\Representation\JobRepresentation->started()
#5 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/html/u...')
#6 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#7 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#8 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#9 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#10 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#11 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#12 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#13 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#14 /var/www/html/uoh-psy/omkVide/index.php(21): Laminas\Mvc\Application->run()
#15 {main}

Amicalement
Jean-Marc

**Comment by samszo** [comment]
L'import OAI UOH est maintenant fonctionnel
