### ISSUE TITLE
Prévisualisation des items

### ISSUE THREAD

**Issue by jmeunierP8** [samszo/Omeka-S-theme-UOH#12]
Dans l'omeka vierge que tu m'a fait, la prévisualisation des items à partir du bouton me renvoie une erreur. 
Exemple :  http://193.54.152.53/uoh-psy/omkVide/s/uoh-pedagotheque-en-psychologie/item/10999

Me renvoie message suivant. L'item appelé semble toujours le même et se produit également lorsqu'on cherche à ouvrir un item à partir du site : 

Omeka\Api\Exception\NotFoundException
Entité Omeka\Entity\Item avec critère {"id":"10980"} non trouvée

Détails :

Omeka\Api\Exception\NotFoundException: Entité Omeka\Entity\Item avec critère {"id":"10980"} non trouvée in /var/www/html/uoh-psy/omkVide/application/src/Api/Adapter/AbstractEntityAdapter.php:686
Stack trace:
#0 /var/www/html/uoh-psy/omkVide/application/src/Api/Adapter/AbstractEntityAdapter.php(404): Omeka\Api\Adapter\AbstractEntityAdapter->findEntity(Array, Object(Omeka\Api\Request))
#1 /var/www/html/uoh-psy/omkVide/application/src/Api/Manager.php(230): Omeka\Api\Adapter\AbstractEntityAdapter->read(Object(Omeka\Api\Request))
#2 /var/www/html/uoh-psy/omkVide/application/src/Api/Manager.php(115): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#3 /var/www/html/uoh-psy/omkVide/application/src/View/Helper/Api.php(69): Omeka\Api\Manager->read('items', '10980', Array)
#4 /var/www/html/uoh-psy/omkVide/themes/uoh/view/omeka/site/item/show.phtml(11): Omeka\View\Helper\Api->read('items', '10980')
#5 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-view/src/Renderer/PhpRenderer.php(505): include('/var/www/html/u...')
#6 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-view/src/View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
#7 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-view/src/View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#8 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-view/src/View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
#9 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-mvc/src/View/Http/DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
#10 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
#11 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-eventmanager/src/EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
#12 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-mvc/src/Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
#13 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-mvc/src/Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
#14 /var/www/html/uoh-psy/omkVide/index.php(21): Laminas\Mvc\Application->run()
#15 {main}

Amicalement
Jean-Marc

**Comment by samszo** [comment]
Les tests de prévisualisation dans le jardin sont OK
