### ISSUE TITLE
Problème d'affichage des items 

### ISSUE THREAD

**Issue by jmeunierP8** [samszo/Omeka-S-theme-UOH#13]
Bonjour Samuel,
J'ai repris le travail sur la pédagothèque, mais je rencontre un problème d'affichage des items voir : [http://193.54.152.53/uoh-psy/omkVide/s/uoh-pedagotheque-en-psychologie/item/10997](http://193.54.152.53/uoh-psy/omkVide/s/uoh-pedagotheque-en-psychologie/item/10997 ). Peux tu voir cela quand tu auras un peu de temps.
Merci d'avance.

**Comment by samszo** [comment]
Bonjour Jean-Marc,
le problème venait d'un mauvais paramètre dans le thème cf. http://193.54.152.53/uoh-psy/omkVide/admin/site/s/uoh-pedagotheque-en-psychologie/theme-settings
L'identifiant de l'item pour évaluer avec des étoiles n'était pas le bon cf. http://193.54.152.53/uoh-psy/omkVide/admin/item/10996
