### ISSUE TITLE
Moissonneur OAI-PMH ne fonctionne pas

### ISSUE THREAD

**Issue by jmeunierP8** [samszo/Omeka-S-theme-UOH#14]
Bonjour Samuel,
Je n'ai plus aucun entrepôt OAI-PMH qui fontionne. Autrefois le problème semblait limité à celui de l'UOH. Voici la liste de ceux que j'ai essayé sur le site vide. 

https://uoh.fr/oai/provider
https://www.canal-u.tv/oai2/?verb=ListSets
http://ori-repository.univ-lille1.fr/OAIHandler
 http://www.unit.eu/ori-oai-repository/OAIHandler

**Comment by samszo** [comment]
Bonjour Jean-MArc,
voici le résultat de quelques tests :
> https://uoh.fr/oai/provider
Le service oai de l'uoh ne répond plus : il y a un problème chez eux...

> https://www.canal-u.tv/oai2/?verb=ListSets
L'adresse qu'il faut mettre dans le module omk est : https://www.canal-u.tv/oai2/
L'import fonctionne en local comme pour les adresses suivantes :
> http://ori-repository.univ-lille1.fr/OAIHandler
> http://www.unit.eu/ori-oai-repository/OAIHandler
Le problème vient sans doute d'une limitation que les techniciens de P8 ont mis sur le serveur.
Je vois avec eux...

**Comment by samszo** [comment]
Après quelques corrections et modification dans le module  l'import de l'OAI uoh fonctionne cf. https://jardindesconnaissances.univ-paris8.fr/uohPsy/admin/item?item_set_id=24257
