### ISSUE TITLE
L'import Zotero ne fonctionne pas

### ISSUE THREAD

**Issue by jmeunierP8** [samszo/Omeka-S-theme-UOH#15]
J'ai fait l'essai avec 

User ID :  1120551
Collection :  key A74J9FLG
API Key :  cX8s4HyWqweZmcckrHXin3Qh

Et j'obtiens : 

Laminas\Http\Client\Adapter\Exception\RuntimeException
Unable to connect to api.zotero.org:443 . Error #0: stream_socket_client(): unable to connect to api.zotero.org:443 (php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution)

Détails :

ErrorException: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-http/src/Client/Adapter/Socket.php:281
Stack trace:
#0 [internal function]: Laminas\Stdlib\ErrorHandler::addError(2, 'stream_socket_c...', '/var/www/html/u...', 281, Array)
#1 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-http/src/Client/Adapter/Socket.php(281): stream_socket_client('api.zotero.org:...', 0, 'php_network_get...', 10, 4, Resource id #903)
#2 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-http/src/Client.php(1445): Laminas\Http\Client\Adapter\Socket->connect('api.zotero.org', 443, true)
#3 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-http/src/Client.php(945): Laminas\Http\Client->doRequest(Object(Laminas\Uri\Http), 'GET', true, Array, '')
#4 /var/www/html/uoh-psy/omkVide/modules/ZoteroImportplus/src/Controller/IndexController.php(172): Laminas\Http\Client->send()
#5 /var/www/html/uoh-psy/omkVide/modules/ZoteroImportplus/src/Controller/IndexController.php(66): ZoteroImportplus\Controller\IndexController->apiKeyIsValid(Array)
#6 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): ZoteroImportplus\Controller\IndexController->importAction()
#7 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#8 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#9 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#10 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#11 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#12 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#13 /var/www/html/uoh-psy/omkVide/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#14 /var/www/html/uoh-psy/omkVide/index.php(21): Laminas\Mvc\Application->run()
#15 {main}

**Comment by samszo** [comment]
J'ai fait un test dans le jardin : ça marche https://jardindesconnaissances.univ-paris8.fr/uohPsy/admin/item?item_set_id=40211
