### ISSUE TITLE
Connexion Loterre ne fonctionne  pas 

### ISSUE THREAD

**Issue by jmeunierP8** [samszo/Omeka-S-theme-UOH#16]
Je viens de tester la connexion à Loterre qui ne marche pas sur le site vide (http://193.54.152.53/uoh-psy/omkVide/admin/item/10997)

Amicalement
Jean-Marc

**Comment by samszo** [comment]
c'est réglé sur le site jardin cf. https://jardindesconnaissances.univ-paris8.fr/uohPsy/s/uoh-pedagotheque-en-psychologie/item/10997
