### ISSUE TITLE
Affichage des vidéos youtube

### ISSUE THREAD

**Issue by jmeunierP8** [samszo/Omeka-S-theme-UOH#18]
Bonjour Samuel,
Dans le cas où l'URI est une vidéo youtube, l'iframe ne fonctionne pas (exemple : https://jardindesconnaissances.univ-paris8.fr/uohPsy/s/uoh-pedagotheque-en-psychologie/item/21272) . Est-il possible de corriger cela  ? 
Amicalement
Jean-Marc

**Comment by samszo** [comment]
OK c'est réglé, le thème affiche les vidéos youtube quand elles sont dans une uri : https://jardindesconnaissances.univ-paris8.fr/uohPsy/s/uoh-pedagotheque-en-psychologie/item/21272
ou quand elle sont dans lom:location cf https://jardindesconnaissances.univ-paris8.fr/uohPsy/s/uoh-pedagotheque-en-psychologie/item/39194
