### ISSUE TITLE
Test import Zotero

### ISSUE THREAD

**Issue by jmeunierP8** [samszo/Omeka-S-theme-UOH#2]
(a) Fonctionne bien et importe les mots clés comme des annotations et crée une item, mais le concept existe, il n'est pas reconnu. J'ai donc des fiches avec des concepts qui ne sont pas liés aux ressources.  Je précise que mes concepts sont déjà pour certains dans des documents zotero récupéré sur wikipedia.
(b) On ne peut pas définir la classe de ressources dans l'importeur Zotero, or il n'y a pas de type concept dans Zotero. IL faut donc créer les concepts dans omeka ou les changer de classe en lot (ce n'est pas difficile). Reste le problème de leur mise en relation avec les ressources.
(c) La date de mise à jour dans l'importeur est la date de modification pour zotero. et du côté d'omeka ? C'est la date de soumission ? 
(d) J'ai essayé de remettre à la main le lien vers les fiches concept, mais je pense qu'il faut alors  supprimer l'annotation. sinon on a un doublon (voir par exemple J'ai essayé de remettre à la main le lien vers les fiches concept liée à [cet item](http://193.54.152.53/uoh-psy/omk/s/uoh-pedagotheque-en-psychologie/item/10926) , mais je pense qu'il faut supprimer l'annotation.

**Comment by samszo** [comment]
> (a) Fonctionne bien et importe les mots clés comme des annotations et crée une item, mais le concept existe, il n'est pas reconnu. J'ai donc des fiches avec des concepts qui ne sont pas liés aux ressources. Je précise que mes concepts sont déjà pour certains dans des documents zotero récupéré sur wikipedia.

Il me faudrait des liens d'exemple car avant la création d'un concept dans omeka on vérifie s'il n'existe pas avant de le recréer.

> (b) On ne peut pas définir la classe de ressources dans l'importeur Zotero, or il n'y a pas de type concept dans Zotero. IL faut donc créer les concepts dans omeka ou les changer de classe en lot (ce n'est pas difficile). Reste le problème de leur mise en relation avec les ressources.

Les concepts sont créés à partir des mots-clef ajouté dans les ressources Zotero.


> (c) La date de mise à jour dans l'importeur est la date de modification pour zotero. et du côté d'omeka ? C'est la date de soumission ?

Il y a une date interne à la base omeka qui n'est pas affichée.

> (d) J'ai essayé de remettre à la main le lien vers les fiches concept, mais je pense qu'il faut alors supprimer l'annotation. sinon on a un doublon (voir par exemple J'ai essayé de remettre à la main le lien vers les fiches concept liée à [cet item](http://193.54.152.53/uoh-psy/omk/s/uoh-pedagotheque-en-psychologie/item/10926) , mais je pense qu'il faut supprimer l'annotation.

Les annotations sont importantes car elles enregistre un point de vue : qui met en relation quelle source avec quelle destination quand.
Si tu les supprime, tu n'auras plus des points de vue mais juste une relation unique ou pas
