### ISSUE TITLE
Affichage des ressources

### ISSUE THREAD

**Issue by jmeunierP8** [samszo/Omeka-S-theme-UOH#3]
- **Dans l'édition des pages**, les blocs ResourceNetworks, l'ajout de collection ne fonctionne qu'après avoir enregister la modification de la page : Voir par exemple[ l'édition  la page d'accueil](http://193.54.152.53/uoh-psy/omk/admin/site/s/uoh-pedagotheque-en-psychologie/page/welcome).  
- Si j'ai compris, l'affichage des onglets avec le réseau dans les ressources est dépendant du thème que tu as créé. Est-ce paramétrable quelque part ?  

- **Dans la partie affichage** des réseau, la liaison d'un mot-clé avec une annotation est gênante. Elle crée un noeud supplémentaire qui pour l'usager n'est pas informatif. On voudrait arriver directement sur le concept. 
- Je n'ai pas vu ou se fait le lien avec wikipédia et Loterre
- Dans les pages ressources, l'icone d'une ressources liée peut-elle être changée pour une icône plus petite et plus design ?  
La question de la taille et du type d'icone est général. Omeka peut-il gérer des icônes par défaut en fonction de la catégorie ? Cela permettrait de distinguer plus facilement les concepts, les auteurs et le ressources.

**Pour les évaluations par les enseignants**, je propose qu'on libelle le boutons par "Conseillé par les profs" avec deux niveaux  (licence &master) et cinq étoiles pour chaque.

**Comment by samszo** [comment]
> * **Dans l'édition des pages**, les blocs ResourceNetworks, l'ajout de collection ne fonctionne qu'après avoir enregister la modification de la page : Voir par exemple[ l'édition  la page d'accueil](http://193.54.152.53/uoh-psy/omk/admin/site/s/uoh-pedagotheque-en-psychologie/page/welcome).

Quand on ajoute une collection, elle est directement modifiable mais elles se positionne au dessus.
Je vais corriger pour qu'elle se positionne en dessous. cf. https://github.com/samszo/Omeka-S-theme-UOH/issues/4

> * Si j'ai compris, l'affichage des onglets avec le réseau dans les ressources est dépendant du thème que tu as créé. Est-ce paramétrable quelque part ?

Que veux-tu paramétrer ? 
Le réseau des ressource peut se mettre dans n'importe qu'elle page en ajoutant le bloc.
Les onglets sont créés dans le code HTML du thème, il faut changer le code pour en ajouter ou en supprimer.

> * **Dans la partie affichage** des réseau, la liaison d'un mot-clé avec une annotation est gênante. Elle crée un noeud supplémentaire qui pour l'usager n'est pas informatif. On voudrait arriver directement sur le concept.

Pour l'instant le fonctionnement est générique : on affiche les ressources liées, celles qui sont liées et ainsi de suite jusqu'à ce qu'il n'y ait plus de ressource ou si on a atteint le niveau max des niveaux.
Tu voudrais qu'on affiche les ressources liées aux annotations sans afficher les annotations ? 

> * Je n'ai pas vu ou se fait le lien avec wikipédia et Loterre

Il faut : 
1. éditer la ressource
2. choisir le modèle de ressource "Concept"
3. remplir les champs correspondant à Loterre et wikipédia
Je vais faire l'étape 2 directement lors de l'importation cf. https://github.com/samszo/Omeka-S-theme-UOH/issues/5

> * Dans les pages ressources, l'icone d'une ressources liée peut-elle être changée pour une icône plus petite et plus design ?

Oui on peut mettre ce qu'on veut, il faut juste les définir

>   La question de la taille et du type d'icone est général. Omeka peut-il gérer des icônes par défaut en fonction de la catégorie ? Cela permettrait de distinguer plus facilement les concepts, les auteurs et le ressources.

Oui c'est possible il faut juste les définir.

> 
> **Pour les évaluations par les enseignants**, je propose qu'on libelle le boutons par "Conseillé par les profs" avec deux niveaux (licence &master) et cinq étoiles pour chaque.
OK je vais faire les modifications cf.  https://github.com/samszo/Omeka-S-theme-UOH/issues/6
