### ISSUE TITLE
Matching auteurs

### ISSUE THREAD

**Issue by jmeunierP8** [samszo/Omeka-S-theme-UOH#9]
Samuel,
J'ai essayé d'enrichir la [notice de Jean Piaget](http://193.54.152.53/uoh-psy/omk/admin/item/10928) (un lien vers une page wikipedia), mais lors de l'import de la notice d'un de ses ouvrages, les enrichissements avaient disparus.  Il n'y a donc pas seulement un matching avec une item existante. Depuis elle s'affiche en erreur dans le front office. Faut-il dans traiter les enrichissements comme des ressources liées et ne pas toucher aux personnes ?  
Amicalement
Jean-Marc

**Comment by samszo** [comment]
C'est réglé, un nouvel import n'écrase plus les modifications sur les personnes
